### ISSUE TITLE
使用 linux-arm64 启动出现问题

### ISSUE THREAD

**Issue by eric2788** [chrononeko/bugtracker#34]
启动错误日志如下:

```log
Failed to inject hooks Error: Failed to load cmnative-linux-arm64.node
    at /llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130286
    at Object.readFileAsync (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:35488)
    at V (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130256)
    at new Promise (<anonymous>)
    at xe (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130142)
    at dl (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:1468)
    at K0 (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:20898)
    at $0 (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:21188)
    at Object.<anonymous> (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:23130)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
```

另外想问一下目前此项目支援 linux-arm64 吗

**Comment by ilharp** [comment]
当前版本控制台打印的所有日志均为正常现象，可以忽略。

之后的版本会屏蔽掉所有输出。

**Comment by eric2788** [comment]
> 当前版本控制台打印的所有日志均为正常现象，可以忽略。
> 
> 之后的版本会屏蔽掉所有输出。

額，不是說Failed to load嗎，所以其實有這個錯誤也可以正常運行嗎

後面還有這種error: 
```
Failed to launch bus: Failed to connect to session bus[88:1011/024438.088007:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

也可以忽略？

**Comment by ilharp** [comment]
是的，所有报错都不会影响 Chronocat 的正常运行。后续版本屏蔽所有输出之后程序将只会输出登录链接，不会再有其他任何内容。

**Comment by eric2788** [comment]
> 是的，所有报错都不会影响 Chronocat 的正常运行。后续版本屏蔽所有输出之后程序将只会输出登录链接，不会再有其他任何内容。

ok原來如此，謝謝解答

我先試試正常登錄，如果沒問題會關掉這個issue

**Comment by eric2788** [comment]
@ilharp 有一個不是很相關的問題，就是 fetch available 的機制 
![image](https://github.com/chrononeko/bugtracker/assets/6276840/d0034bc8-c51c-480e-9a52-fc470fa8104a)
目前采用强制 http 連綫，但我使用了 https only 作爲我的控制臺網址，導致無法進行 fetch
不知未來會否支持https? 畢竟有時候想外部使用但只能用http還是有安全問題

**Comment by ilharp** [comment]
目前，我们反对在外部网络环境使用 Chronocat 管理员服务。如果你有这个需求的话，直接拿出 [`login.html`](https://github.com/chrononeko/chronocat/blob/master/packages/core/static/login.html) 改一改然后挂一个就可以了，这个 html 文件不依赖其他文件，不受跨域问题影响。

**Comment by eric2788** [comment]
是的 我最後繞過了html直接用api請求完成了登錄

說不定可能之後可以有外部登錄？當然網站需要被密碼保護之類

anyways 我登錄沒問題，先關issue
