### ISSUE TITLE
使用手机浏览器经由公网无加密登录时报错

### ISSUE THREAD

**Issue by jiangyin14** [chrononeko/bugtracker#39]
日志如下

’’’
[LiteLoader] Found plugin: LiteLoader 插件市场
访问此链接以登录：
http://127.0.0.1:16340/login#127.0.0.1:16340@4c800319bdb1eb00b9b787a5efd9a3c6a990c8d981a62a23fd0b78cad4d69591
[LiteLoader] Found plugin: Chronocat
[LiteLoader] Done! 4 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
Failed to inject hooks Error: Failed to load cmnative-linux-x64.node
    at /llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130286
    at Object.readFileAsync (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:35488)
    at V (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130256)
    at new Promise (<anonymous>)
    at xe (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130142)
    at dl (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:1468)
    at K0 (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:20789)
    at $0 (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:21079)
    at Object.<anonymous> (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:22990)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
[80:1011/145111.012414:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[80:1011/145111.012513:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[80:1011/145111.034371:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[80:1011/145111.034423:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[128:1011/145111.053720:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[80:1011/145111.084891:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[80:1011/145111.105421:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[80:1011/145111.110596:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[80:1011/145111.115028:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[80:1011/145111.115260:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[80:1011/145111.115793:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

(qq:80): libappindicator-WARNING **: 14:51:11.126: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”

(qq:80): LIBDBUSMENU-GLIB-WARNING **: 14:51:11.126: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”
[80:1011/145111.127066:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: unknown error type: 
quickLogin error:  cannot find single quick login btn
linux-bugly: init bugly ...
[BuglyManager.cpp][InitBuglyManager][198]InitBuglyManager path: /chrono/.config/QQ/crash_files/
[BuglyService.cpp][registBugly][589]set signal stack
[BuglyService.cpp][registSignalHandler][520]regist native handler
[BuglyService.cpp][setParam][618]setParam, key:appVersion, value:3.1.2-13107..
signal success
linux-bugly: init bugly done.
Chronocat login service stopped due to authorization
[130:1011/145218.477552:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[130:1011/145218.482091:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[130:1011/145218.486166:ERROR:broker_posix.cc(46)] Received unexpected number of handles
14:52:21.737 › [HotUpdater][clearOldVersions] start clear old version files
[80:1011/145221.995052:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[80:1011/145221.995162:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
[NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/chrono/.config/QQ/crash_files/rqd_record.eup.
[NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
’’’

启动服务（docker）时候给出如下输出，把登录链接中的127.0.0.1更换成域名（公网ip也尝试了），成功加载扫码登录，且扫码成功。随后浏览器中显示server disconnect，
刷新无法打开登录前页面（加载不出且无日志输出）
重启docker后再试，出现了快捷登录对应账号的按钮，但是点击后同样给出如上报错且手机浏览器表现一致（无法加载出页面）

**Comment by ilharp** [comment]
`server disconnected` 表示登录成功，登录服务器已关闭。接下来你可正常使用 Chronocat。
