### ISSUE TITLE
Bug: Linux云服务器中运行docker出现问题

### ISSUE THREAD

**Issue by fu050409** [chrononeko/bugtracker#40]
```
root@hcss-ecs-ccfa:~/chronocat# docker run -it   --name chronocat   -p 16530:16530   -p 5500:5500   -p 16340:16340   -v ./config:/chrono/.chronocat/config   -v ./qq:/chrono/.config/QQ   chronoc/at
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Oct 11 15:42:08 0d52b845b75b syslog-ng[14]: syslog-ng starting up; version='3.35.1'
*** Running /etc/my_init.d/20_setuser...
设置用户 chronocat 为 911:1000
usermod: no changes
设置 UMASK 为 002
设置用户文件夹所有者
设置用户文件夹权限
*** Booting runit daemon...
*** Runit started as PID 40
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Oct 11 15:42:09 0d52b845b75b cron[47]: (CRON) INFO (pidfile fd = 3)
Oct 11 15:42:09 0d52b845b75b cron[47]: (CRON) INFO (Running @reboot jobs)
Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
Failed to launch bus: Failed to connect to session bus[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at /opt/QQ.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
访问此链接以登录：
http://127.0.0.1:16340/login#127.0.0.1:16340@c6c76ad96b22934ed498ce40399ece3152442f792a8a107cee3bfaf532cc3568
[LiteLoader] Found plugin: Chronocat
[LiteLoader] Done! 4 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
Failed to inject hooks Error: Failed to load cmnative-linux-x64.node
    at /llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130286
    at Object.readFileAsync (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:35488)
    at V (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130256)
    at new Promise (<anonymous>)
    at xe (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130142)
    at dl (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:1468)
    at K0 (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:20898)
    at $0 (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:21188)
    at Object.<anonymous> (/llqqnt/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:23130)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
[86:1011/154211.787089:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[86:1011/154211.806628:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[86:1011/154211.808714:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[86:1011/154211.809326:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[134:1011/154211.821397:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is
[86:1011/154211.838487:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[86:1011/154211.857561:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[86:1011/154211.862515:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[86:1011/154211.862699:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[86:1011/154211.862867:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[86:1011/154211.863104:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[86:1011/154211.880468:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: unknown error type:

(qq:86): libappindicator-WARNING **: 15:42:11.882: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”

(qq:86): LIBDBUSMENU-GLIB-WARNING **: 15:42:11.883: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”
```

**Comment by fu050409** [comment]
是不支持无桌面环境的状态吗？

**Comment by dollars0427** [comment]
個人實際使用也看到這個報錯，但似乎不影響使用。
只要複製貼上
http://127.0.0.1:16340/login#127.0.0.1:16340@c6c76ad96b22934ed498ce40399ece3152442f792a8a107cee3bfaf532cc3568
(127.0.0.1的部份改為你服務器的公網IP)，掃碼登入就能正常使用了。

**Comment by jiangyin14** [comment]
有方案了踢我
其实你只要点开#39就会发现在你发之前半个小时我刚针对这个问题发了issue

**Comment by ilharp** [comment]
Duplicate of #34

https://github.com/chrononeko/bugtracker/issues/34#issuecomment-1756736614
