### ISSUE TITLE
无法登录QQ

### ISSUE THREAD

**Issue by Shua-github** [chrononeko/bugtracker#83]
可以到达登录界面，但是点击登录会
![image](https://github.com/user-attachments/assets/cf22e236-208d-4f8b-a7e4-fa67607a6c47)
以下是日志:
PS C:\Program Files\Tencent\QQNT> .\QQ.exe --enable-logging
PS C:\Program Files\Tencent\QQNT> [LiteLoader] Found Plugin: 防撤回
[LiteLoader] Found Plugin: Audio Sender
[LiteLoader] Found Plugin: Chii DevTools
[LiteLoader] Found Plugin: 演示模式
[LiteLoader] Found Plugin: 使用自定义浏览器打开链接并跳过拦截页
[LiteLoader] Found Plugin: Euphony
[LiteLoader] Found Plugin: 自动抢红包
[LiteLoader] Found Plugin: JustF5
[LiteLoader] Found Plugin: 插件列表查看
[LiteLoader] Found Plugin: Chronocat
[LiteLoader] Found Plugin: Chronocat Engine: Chronocat-Api
[LiteLoader] Found Plugin: Chronocat Engine: Chronocat-Event
[LiteLoader] Found Plugin: Chronocat Engine: Crychiccat
[LiteLoader] Found Plugin: Chronocat Engine: Media
[LiteLoader] Found Plugin: 轻量工具箱
[LiteLoader] Found Plugin: NapCatQQ
2024-12-03 08:58:07 starting server at localhost:61059/
[Grab-Redpack] 启动！
[Grab-Redpack] 现在执行initConfig方法
[Grab-Redpack] 当前的配置文件为
{
  isActive: true,
  useRandomDelay: true,
  delayLowerBound: '3000',
  delayUpperBound: '4000',
  useRandomDelayForSend: false,
  delayLowerBoundForSend: '2000',
  delayUpperBoundForSend: '10000',
  avoidKeyWords: [ 'test', '测试', '不' ],
  avoidGroups: [ '518662028' ],
  listenKeyWords: [],
  listenGroups: [],
  useSelfNotice: false,
  thanksMsgs: [],
  isActiveAllGroups: true,
  blockType: '2',
  pluginPath: 'C:\\Users\\CHA_s.DESKTOP-SJ4A095\\Documents\\LiteloaderQQNT\\plugins\\grab_redbag',
  configPath: 'C:\\Users\\CHA_s.DESKTOP-SJ4A095\\Documents\\LiteloaderQQNT\\plugins\\grab_redbag\\config.json'
}
[Grab-Redpack] 配置初始化完毕

​‌​​
​‌​​strong.lowcost.bot.ilharp.satori.strong.strong.reliable.evolutionary.reliable.co
​‌​​nsistency.strong.reliable.bot.safe.koishi.engine.ilharp.koishi.reliable.strong.c
​‌​​hronocat______.low__cost.lowcost.strong.consistency.chr______onocat.sato__ri.saf
​‌​​e.sator/ ____/i.k/ /_oish_____i.____sato____ri.____ilh/ ____/ar____p_.l/ /_owcos
​‌​​t.reli/ /able.il/ __ \ha/ ___/r/ __ \p./ __ \i/ __ \l/ /harp.b/ __ `/o/ __/t.bot
​‌​​.safe/ /___.low/ /c/ /o/ /st.i/ /_/ /l/ /h/ // /_/ // /___arp/ /_/ /./ /_chronoc
​‌​​at.en\____/gin/_/e/_/./_/consi\____/s/_/t/_/e\____/n\____/cy.\__,_/il\__/harp.bo
​‌​​t.strong.engine.convenient.evolutionary.satori.bot.satori.bot.satori.strong.engi
​‌​​ne.safe.reliable.satori.bot.satori.ilharp.ilharp.bot.consistency.convenient.evol
​‌​​
​‌​​
​‌​​
[    ][12-03 08:58:08][I][CH0000] Chronocat 0.2.19
[    ][12-03 08:58:08][I][CH0000] 当左侧错误指示灯亮起时，点击错误码以检查说明。
[NapCat] [Info] 开始初始化NapCat
[    ][12-03 08:58:08][I][CH0000] 加载引擎 engine-chronocat-api v0.2.19
[    ][12-03 08:58:08][I][CH0000] 加载引擎 engine-chronocat-event v0.2.19
[    ][12-03 08:58:08][I][CH0000] 加载引擎 engine-crychiccat v0.2.19
[    ][12-03 08:58:08][I][CH0000] 加载引擎 engine-media v0.2.19
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82968)
    at WebContents.emit (node:events:519:28)
Proxy... Event: NodeIQQNTWrapperSession/create
++++++registerSimMojoCallback+++++,
create callbak source success
Proxy... Event: NodeIKernelLoginService/get
[NapCat] Fuck LoginService Loading...
NapCat Framework App Loading...
[NapCat] [Error] unhandledRejection: TypeError: Cannot destructure property 'members' of 't' as it is undefined.
    at K (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Event\src\chronocat-event.engine.js:4:7336)
    at Object.handler (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Event\src\chronocat-event.engine.js:4:6172)
    at i (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Event\src\chronocat-event.engine.js:1:570)
    at WebContents.<anonymous> (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Event\src\chronocat-event.engine.js:1:820)
    at WebContents.send (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Api\src\chronocat-api.engine.js:12:2953)
    at g.sender (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1:872695)
    at g.emit (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1:868444)
    at g.handleInvoke (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1:868007)
[NapCat] [Error] unhandledRejection: TypeError: Cannot destructure property 'members' of 'i' as it is undefined.
    at gs (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Api\src\chronocat-api.engine.js:17:7365)
    at Object.handler (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Api\src\chronocat-api.engine.js:17:5846)
    at n (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Api\src\chronocat-api.engine.js:12:2737)
    at WebContents.send (C:\Users\CHA_s.DESKTOP-SJ4A095\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-Plugin-Chronocat-Engine-Chronocat-Api\src\chronocat-api.engine.js:12:2990)
    at g.sender (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1:872695)
    at g.emit (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1:868444)
    at g.handleInvoke (C:\Program Files\Tencent\QQNT\versions\9.9.16-29927\resources\app\application.asar\203.background.js:1:868007)
2024-12-03 08:58:09 target g-nJtv: connected

**Comment by Shua-github** [comment]
QQNT版本号:9.9.16-29927
Chronocat版本号:0.2.19
LiteLoaderQQNT版本号:1.2.3

**Comment by Shua-github** [comment]
Chronocat版本号:0.2.19
LiteLoaderQQNT版本号:1.2.3
QQNT版本号:9.9.16_29927

**Comment by ilharp** [comment]
Crychiccat 插件删掉

Crychiccat 没适配新版本，最近忙，懒得搞了

**Comment by Shua-github** [comment]
> Crychiccat 插件删掉
> 
> Crychiccat 没适配新版本，最近忙，懒得搞了

好的，可以了，谢谢
